dev: true
max_suggested_results: 10
new_post_visibility_threshold_minutes: 15

# Delete thumbnails and source files on post delete
# Original functionality is no, to mitigate the impacts of admins going
# on unchecked post purges.
delete_source_files: no

thumbnails:
    min_file_size: 6000000
    avatar_width: 300
    avatar_height: 300
    post_width: 300
    post_height: 300

# settings used to download files from the web on behalf of the api users
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
max_dl_filesize: 25.0E+6 # maximum filesize limit in bytes

# automatically convert animated GIF uploads to video formats
convert:
   gif:
     to_webm: false
     to_mp4: false

# allow posts to be uploaded even if some image processing errors occur
allow_broken_uploads: false

# used to send password reset e-mails
smtp:
    host: # example: localhost
    port: # example: 25
    user: # example: bot
    pass: # example: groovy123
    from: # example: noreply@example.com
    # if host is left empty the password reset feature will be disabled,
    # in which case it is recommended to fill contactEmail so that users
    # know who to contact when they want to reset their password

# example: bob@example.com. Meant for manual password reset procedures
contact_email: ""
can_send_mails: false

enable_safety: false

tag_name_regex: '^[a-z0-9_-]{1,80}$'
tag_category_name_regex: '^[a-zA-Z0-9_-]{1,80}$'

pool_name_regex: '^[a-zA-Z0-9_-]{1,80}$'
pool_category_name_regex: '^[a-zA-Z0-9_-]{1,80}$'

# don't make these more restrictive unless you want to annoy people; if you do
# customize them, make sure to update the instructions in the registration form
# template as well.
password_regex: '^.{8,100}$'
user_name_regex: '^[a-zA-Z0-9_]{1,32}$'

# webhooks to call when events occur (such as post/tag/user/etc. changes)
# the listed urls will be called with a HTTP POST request with a payload
# containing a snapshot resource as JSON. See doc/API.md for details
webhooks:
    # - https://api.example.com/webhooks/

default_rank: regular

privileges:
    # Registration permission
    'users:create:self':            anonymous

    'users:create:any':             administrator
    'users:list':                   power
    'users:view':                   anonymous
    'users:edit:any:name':          moderator
    'users:edit:any:pass':          moderator
    'users:edit:any:email':         moderator
    'users:edit:any:avatar':        moderator
    'users:edit:any:rank':          moderator
    'users:edit:self:name':         regular
    'users:edit:self:pass':         regular
    'users:edit:self:email':        regular
    'users:edit:self:avatar':       regular

    # One can't promote themselves or anyone to a higher rank than their own
    'users:edit:self:rank':         moderator

    'users:delete:any':             administrator
    'users:delete:self':            regular

    'user_tokens:list:any':         administrator
    'user_tokens:list:self':        regular
    'user_tokens:create:any':       administrator
    'user_tokens:create:self':      regular
    'user_tokens:edit:any':         administrator
    'user_tokens:edit:self':        regular
    'user_tokens:delete:any':       administrator
    'user_tokens:delete:self':      regular

    #'posts:create':                 regular
    'posts:create:anonymous':       power
    'posts:create:identified':      power
    'posts:list':                   anonymous
    'posts:reverse_search':         anonymous
    'posts:view':                   anonymous
    'posts:view:featured':          anonymous
    'posts:view:similar':           anonymous
    'posts:edit:content':           moderator
    'posts:edit:flags':             power
    'posts:edit:notes':             power
    'posts:edit:relations':         power
    'posts:edit:safety':            power
    'posts:edit:source':            power
    'posts:edit:tags':              power
    'posts:edit:thumbnail':         power
    'posts:feature':                administrator
    'posts:delete':                 moderator
    'posts:score':                  regular
    'posts:merge':                  moderator
    'posts:favorite':               regular
    'posts:bulk-edit:tags':         power
    'posts:bulk-edit:safety':       power
    'posts:bulk-edit:delete':       power

    # Can see new posts in gallery
    'posts:list:new':               anonymous

    'tags:create':                  power
    'tags:edit:names':              power
    'tags:edit:category':           power
    'tags:edit:description':        power
    'tags:edit:implications':       power
    'tags:edit:suggestions':        power
    'tags:list':                    anonymous
    'tags:view':                    anonymous
    'tags:merge':                   moderator
    'tags:delete':                  moderator

    'tag_categories:create':        moderator
    'tag_categories:edit:name':     moderator
    'tag_categories:edit:color':    moderator
    'tag_categories:edit:order':    moderator
    'tag_categories:list':          anonymous
    'tag_categories:view':          anonymous
    'tag_categories:delete':        moderator
    'tag_categories:set_default':   moderator

    'metrics:create':               moderator
    'metrics:edit:bounds':          moderator
    'metrics:edit:posts':           moderator
    'metrics:list':                 moderator
    'metrics:delete':               moderator

    'pools:create':                 power
    'pools:edit:names':             power
    'pools:edit:category':          power
    'pools:edit:description':       power
    'pools:edit:posts':             power
    'pools:list':                   regular
    'pools:view':                   anonymous
    'pools:merge':                  moderator
    'pools:delete':                 moderator

    'pool_categories:create':       moderator
    'pool_categories:edit:name':    moderator
    'pool_categories:edit:color':   moderator
    'pool_categories:list':         anonymous
    'pool_categories:view':         anonymous
    'pool_categories:delete':       moderator
    'pool_categories:set_default':  moderator

    'comments:create':              power
    'comments:delete:any':          moderator
    'comments:delete:own':          power
    'comments:edit:any':            moderator
    'comments:edit:own':            power
    'comments:list':                anonymous
    'comments:view':                anonymous
    'comments:score':               regular

    'snapshots:list':               power

    'uploads:create':               power
    'uploads:use_downloader':       administrator

## ONLY SET THESE IF DEPLOYING OUTSIDE OF DOCKER
#debug: 0 # generate server logs?
#show_sql: 0 # show sql in server logs?
#data_url: /data/
#data_dir: /var/www/data
## usage: schema://user:password@host:port/database_name
## example: postgres://szuru:dog@localhost:5432/szuru_test
#database:
