<nav id='top-navigation' class='buttons'><!--
    --><button id="mobile-navigation-toggle"><!--
        --><span class="site-name"><%- ctx.name %></span><!--
        --><span class="toggle-icon"><i class="la la-bars"></i></span><!--
    --></button><!--
    --><ul id="nav-left" class="nav-bar"><!--
        --><% for (let item of ctx.items) { %><!--
            --><% if (item.text.includes("left")) { %><!--
                --><% if (item.available) { %><!--
                    --><li data-name='<%- item.key %>'><!--
                        --><a href='<%- item.url %>' title='<%- item.title %>' accesskey='<%- item.accessKey %>'><!--
                            --><% if (item.imageUrl) { print(ctx.makeThumbnail(item.imageUrl)); } %><!--
                            --><span class='text'><%= item.text.replace("left", "") %></span><!--
                        --></a><!--
                    --></li><!--
                --><% } %><!--
            --><% } %><!--
        --><% } %><!--
    --></ul><!--
    --><ul id="nav-right" class="nav-bar"><!--
        --><% for (let item of ctx.items) { %><!--
            --><% if (item.text.includes("right")) { %><!--
                --><% if (item.available) { %><!--
                    --><li data-name='<%- item.key %>'><!--
                        --><a href='<%- item.url %>' title='<%- item.title %>' accesskey='<%- item.accessKey %>'><!--
                            --><% if (item.imageUrl) { print(ctx.makeThumbnail(item.imageUrl)); } %><!--
                            --><span class='text'><%= item.text.replace("right", "") %></span><!--
                        --></a><!--
                    --></li><!--
                --><% } %><!--
            --><% } %><!--
        --><% } %><!--
    --></ul><!--
--></nav>
